package com.norsemenapps.freysweather.model.model.db;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here

import android.os.Parcel;
import android.os.Parcelable;
// KEEP INCLUDES END


/**
 * Entity mapped to table "FORECAST_PLACE".
 */
public class ForecastPlace implements Parcelable {

    private Long id;
    private String name;
    private Integer order;
    private String path;
    private boolean bigCard;
    private boolean isCurrentLocation;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public ForecastPlace() {
    }

    public ForecastPlace(Long id) {
        this.id = id;
    }

    public ForecastPlace(Long id, String name, Integer order, String path, boolean bigCard, boolean isCurrentLocation) {
        this.id = id;
        this.name = name;
        this.order = order;
        this.path = path;
        this.bigCard = bigCard;
        this.isCurrentLocation = isCurrentLocation;
    }


    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public Integer getOrder() {
        return order;
    }

    public void setOrder(Integer order) {
        this.order = order;
    }

    public String getPath() {
        return path;
    }

    public void setPath(String path) {
        this.path = path;
    }

    public boolean getBigCard() {
        return bigCard;
    }

    public void setBigCard(boolean bigCard) {
        this.bigCard = bigCard;
    }

    public boolean getIsCurrentLocation() {
        return isCurrentLocation;
    }

    public void setIsCurrentLocation(boolean isCurrentLocation) {
        this.isCurrentLocation = isCurrentLocation;
    }


    // KEEP METHODS - put your custom methods here
    protected ForecastPlace(Parcel in) {
        name = in.readString();
        path = in.readString();
        bigCard = in.readByte() != 0;
        isCurrentLocation = in.readByte() != 0;
    }

    public static final Creator<ForecastPlace> CREATOR = new Creator<ForecastPlace>() {
        @Override
        public ForecastPlace createFromParcel(Parcel in) {
            return new ForecastPlace(in);
        }

        @Override
        public ForecastPlace[] newArray(int size) {
            return new ForecastPlace[size];
        }
    };

    @Override
    public int describeContents() {
        return 0;
    }

    @Override
    public void writeToParcel(Parcel dest, int flags) {
        dest.writeString(name);
        dest.writeString(path);
        dest.writeByte((byte) (bigCard ? 1 : 0));
        dest.writeByte((byte) (isCurrentLocation ? 1 : 0));
    }
    // KEEP METHODS END

}
